# fly.toml app configuration file generated for thecloudmind-api on 2026-03-27T23:41:13+05:30
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'thecloudmind-api'
primary_region = 'bom'

[build]

[http_service]
  internal_port = 8000
  force_https = true
  auto_stop_machines = false
  auto_start_machines = true
  min_machines_running = 1

  [http_service.concurrency]
    type = 'connections'
    hard_limit = 100
    soft_limit = 80

  [[http_service.checks]]
    grace_period = "15s"
    interval = "30s"
    method = "GET"
    path = "/health"
    protocol = "http"
    timeout = "10s"

[[vm]]
  memory = "2gb"
  cpu_kind = "performance"
  cpus = 1
